{% set version = "dev" %}

package:
  name: nco
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - antlr 2.7.7
    - curl
    - expat
    - gsl
    - hdf5
    - libnetcdf
    - udunits2
    - zlib
  run:
    - curl
    - expat
    - gsl
    - hdf5
    - libnetcdf
    - udunits2

test:
  source_files:
    - data
  commands:
    - ncks --help
    - ncap2 --help
    - ncks -M "http://tds.marine.rutgers.edu/thredds/dodsC/roms/espresso/2013_da/his/ESPRESSO_Real-Time_v2_History_Best"
